services:

    #
    # Event Listeners
    #
    elcodi.core.cart_coupon.event_listener.cart:
        class: %elcodi.core.cart_coupon.event_listener.cart.class%
        arguments:
            coupon_manager: @elcodi.core.coupon.service.coupon_manager
            cart_coupon_manager: @elcodi.core.cart_coupon.service.cart_coupon_manager
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: onCartOnLoad }

    elcodi.core.cart_coupon.event_listener.order:
        class: %elcodi.core.cart_coupon.event_listener.order.class%
        arguments:
            coupon_event_dispatcher: @elcodi.core.coupon.event_dispatchers.coupon
            order_coupon_factory: @elcodi.core.cart_coupon.factory.order_coupon
            cart_coupon_manager: @elcodi.core.cart_coupon.service.cart_coupon_manager
            manager: @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: order.oncreated, method: onOrderOnCreatedEventCouponsValue }
            - { name: kernel.event_listener, event: order.oncreated, method: onOrderOnCreatedEventTransferCoupons }
