services:

    #
    # EventDispatchers
    #
    elcodi.event_dispatcher.cart_coupon:
        class: %elcodi.event_dispatcher.cart_coupon.class%
        parent: elcodi.event_dispatcher.abstract

    elcodi.event_dispatcher.order_coupon:
        class: %elcodi.event_dispatcher.order_coupon.class%
        parent: elcodi.event_dispatcher.abstract
