services:

    #
    # Object Managers
    #
    elcodi.object_manager.cart_coupon:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.cart_coupon.entity.cart_coupon.class% ]

    elcodi.object_manager.order_coupon:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.cart_coupon.entity.order_coupon.class% ]
