services:

    #
    # Repositories
    #

    #
    # Repository for entity cart_coupon
    #
    elcodi.repository.cart_coupon:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.cart_coupon.entity.cart_coupon.class% ]

    #
    # Repository for entity order_coupon
    #
    elcodi.repository.order_coupon:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.cart_coupon.entity.order_coupon.class% ]
