services:

    #
    # Services
    #
    elcodi.manager.cart_coupon:
        class: %elcodi.manager.cart_coupon.class%
        arguments:
            - @elcodi.event_dispatcher.cart_coupon
            - @elcodi.manager.coupon
            - @elcodi.repository.coupon
            - @elcodi.repository.cart_coupon

    elcodi.manager.order_coupon:
        class: %elcodi.manager.order_coupon.class%
        arguments:
            - @elcodi.repository.order_coupon

    elcodi.manager.cart_coupon_rule:
        class: %elcodi.manager.cart_coupon_rule.class%
        arguments:
            - @elcodi.manager.rule
