services:

    #
    # Services
    #
    elcodi.core.cart_coupon.service.cart_coupon_manager:
        class: %elcodi.core.cart_coupon.service.cart_coupon_manager.class%
        arguments:
            cart_coupon_event_dispatcher: @elcodi.cart_coupon_event_dispatcher
            coupon_manager: @elcodi.core.coupon.service.coupon_manager
            coupon_repository: @elcodi.repository.coupon
            cart_coupon_repository: @elcodi.repository.cart_coupon

    elcodi.cart_coupon_manager:
        alias: elcodi.core.cart_coupon.service.cart_coupon_manager

    elcodi.core.cart_coupon.service.order_coupon_manager:
        class: %elcodi.core.cart_coupon.service.order_coupon_manager.class%
        arguments:
            order_coupon_repository: @elcodi.repository.order_coupon

    elcodi.order_coupon_manager:
        alias: elcodi.core.cart_coupon.service.order_coupon_manager

    elcodi.core.cart_coupon.service.cart_coupon_rule_manager:
        class: %elcodi.core.cart_coupon.service.cart_coupon_rule_manager.class%
        arguments:
            rule_manager: @elcodi.rule_manager

    elcodi.cart_coupon_rule_manager:
        alias: elcodi.core.cart_coupon.service.cart_coupon_rule_manager
