services:

    #
    # Services
    #
    elcodi.cart_coupon_manager:
        class: %elcodi.cart_coupon_manager.class%
        arguments:
            cart_coupon_event_dispatcher: @elcodi.event_dispatcher.cart_coupon
            coupon_manager: @elcodi.coupon_manager
            coupon_repository: @elcodi.repository.coupon
            cart_coupon_repository: @elcodi.repository.cart_coupon

    elcodi.order_coupon_manager:
        class: %elcodi.order_coupon_manager.class%
        arguments:
            order_coupon_repository: @elcodi.repository.order_coupon

    elcodi.cart_coupon_rule_manager:
        class: %elcodi.cart_coupon_rule_manager.class%
        arguments:
            rule_manager: @elcodi.rule_manager
